<?php

return [
    'eyebrow' => 'Core workflow',
    'title' => 'Order Checking',
    'description' => 'Select receiver, product, and unit data from Sisahygo, review, then submit one checking request.',
    'loading' => 'Loading',
    'status' => ['checking' => 'Checking'],
    'environment' => ['title' => 'Connected to Sisahygo Client API', 'body' => 'Receiver, product, and unit data load through the selected client account credential.'],
    'unavailable' => ['title' => 'Order checking is not ready', 'no_sender' => 'This client account is not allowed to send shipments. Contact your Sisahygo Connect administrator.', 'no_credential' => 'This client account does not have an active API credential.', 'integration' => 'Sisahygo integration data cannot be prepared right now.'],
    'sender' => ['label' => 'Sender', 'placeholder' => 'Select sender'],
    'receiver' => ['title' => '1. Receiver', 'description' => 'Search Sisahygo receivers scoped by the sender API key.', 'search_label' => 'Search receiver', 'search_placeholder' => 'Receiver name, phone, or ID', 'search_hint' => 'Type at least 2 characters. Search is debounced.', 'min_search' => 'Type at least 2 characters to search receivers.', 'no_results' => 'No matching receivers found.', 'selected_label' => 'Selected receiver', 'change' => 'Change receiver', 'empty_selected' => 'No receiver selected yet.', 'no_phone' => 'No phone in result', 'branch_derived' => 'Destination branch is derived by Sisahygo from the receiver; Connect does not send branch_rec_id.'],
    'products' => ['search_label' => 'Search products', 'search_placeholder' => 'Product name or Product ID', 'min_search' => 'Type at least 2 characters to search products.', 'no_results' => 'No matching products found.'],
    'items' => ['title' => '2. Items', 'description' => 'Select products authorized by Sisahygo, then enter quantity and optional line references.', 'product' => 'Product', 'product_empty' => 'Select a product from search results', 'unit' => 'Unit', 'unit_placeholder' => 'Select unit', 'amount' => 'Amount', 'remark' => 'Item remark', 'remark_placeholder' => 'Example: 100 sheets or fragile', 'client_line_id' => 'Line ID', 'client_item_no' => 'Item No.', 'client_product_code' => 'Product Code', 'remove' => 'Remove'],
    'reference' => ['title' => '3. Remark and reference', 'description' => 'Connect requires a client reference for timeout reconciliation without claiming idempotency.', 'reference_label' => 'Client reference', 'remark_label' => 'Remark', 'remark_placeholder' => 'Example: deliver before 15:00, contact Mali'],
    'review' => ['title' => '4. Review and confirm', 'description' => 'Send one request to the Sisahygo Client API when the form is complete.', 'receiver' => 'Receiver', 'reference' => 'Reference', 'items' => 'Items', 'status' => 'Readiness', 'missing' => 'Missing', 'ready' => 'Ready to submit', 'not_ready' => 'More information needed', 'submit' => 'Submit order checking request', 'submitting' => 'Submitting...', 'item_count' => ':count item(s)'],
    'progress' => ['title' => 'Progress', 'receiver' => 'Select receiver', 'items' => 'Add items', 'reference' => 'Add reference', 'review' => 'Ready to confirm'],
    'help' => ['title' => 'What Connect sends', 'body' => 'Connect sends only customer_rec_id, client_reference_no, remark, and item data to Core API.', 'validation_body' => 'Core remains authoritative for receiver, product, unit, and duplicate reference validation.'],
    'success' => ['title' => 'Sisahygo received the checking request', 'body' => 'The order is waiting for staff verification. This does not mean shipment acceptance, loading, or transport completion.', 'initial_status' => 'Initial status', 'core_reference' => 'Sisahygo reference', 'next_action' => 'Back to dashboard', 'create_another' => 'Create another order'],
    'unknown' => ['title' => 'Submission result is unknown', 'body' => 'The connection failed after the request started. Connect will not submit again automatically. Check this client reference before creating another order.', 'reconcile' => 'Check by reference', 'reconciling' => 'Checking...', 'not_found' => 'No order was found for this reference yet. Check with operations before submitting again.'],
    'errors' => ['receiver_search_failed' => 'Receiver search is unavailable right now.', 'product_search_failed' => 'Product search is unavailable right now.', 'validation_failed' => 'Some information is invalid. Please review the form.', 'authentication' => 'The API credential is invalid or no longer authorized.', 'authorization' => 'This account is not authorized for this API action.', 'rate_limited' => 'Too many API requests. Please wait and try again.', 'server' => 'Sisahygo could not process the request right now. Reference: :correlation', 'recoverable' => 'The order could not be submitted right now. Review and try again.'],
    'validation' => ['submit_in_progress' => 'This order is already being submitted. Please wait.', 'sender_unavailable' => 'This client account is not allowed to send shipments.', 'sender_required' => 'Please select a sender.', 'sender_invalid' => 'The selected sender is not authorized for this account.', 'receiver_invalid' => 'The selected receiver is not available to this account.', 'product_invalid' => 'This product or product/unit pair is not authorized for the sender.', 'unit_invalid' => 'The selected unit is invalid.', 'selectedReceiver.customer_id.required' => 'Please select a receiver.', 'client_reference_no.required' => 'Please enter a client reference.', 'client_reference_no.max' => 'The client reference must not exceed 100 characters.', 'remark.max' => 'The remark must not exceed 150 characters.', 'items.required' => 'Please add at least one item.', 'items.min' => 'Please add at least one item.', 'items.max' => 'Items must not exceed 200 rows.', 'items.*.product_id.required' => 'Please select a product.', 'items.*.unit_id.required' => 'Please select a unit.', 'items.*.amount.required' => 'Please enter an amount.', 'items.*.amount.min' => 'Amount must be at least 0.0001.', 'items.*.remark.max' => 'Item remark must not exceed 200 characters.', 'items.*.client_line_id.max' => 'Line ID must not exceed 100 characters.', 'items.*.client_item_no.max' => 'Item No. must not exceed 100 characters.', 'items.*.client_product_code.max' => 'Product Code must not exceed 100 characters.'],
];
